ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 192.168.0.0/16
ipv4NativeRoutingCIDR: "192.168.0.0/16"
kubeProxyReplacement: true
routingMode: native
autoDirectNodeRoutes: true
# only expose loadBalancerClass=io.cilium/l2-announcer
defaultLBServiceIPAM: none
debug:
  enabled: true
l2announcements:
  enabled: true
l2NeighDiscovery:
  enabled: true
externalIPs:
  enabled: true
hubble:
  relay:
    enabled: true


loadBalancer:
  # while the loadbalancer NIC can be toggled to run with lower MTU to support XDP, we still want to use jumbo frames for the pod network NIC
  # TODO: XDP is currently not working with pods being on other nodes than the one advertising the virtual IP.
  # Need to investigate why traffic is dropped
  # acceleration: best-effort
  algorithm: maglev
  mode: dsr
  dsrDispatch: geneve
tunnelProtocol: geneve

bpf:
  lbModeAnnotation: true
  enableTCX: true
  masquerade: true

nodePort:
  directRoutingDevice: enp7s0
