# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lbaas-pool"
spec:
  blocks:
  - cidr: "172.16.0.96/27"
  serviceSelector:
    matchExpressions:
      - key: cilium.stackit.cloud/internal
        operator: Exists
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: loadbalancer
spec:
  # direct routing device
  interfaces:
    - enp7s0
  serviceSelector:
    matchExpressions:
      - key: cilium.stackit.cloud/internal
        operator: Exists
  loadBalancerIPs: true

