apiVersion: apps/v1
kind: Deployment
metadata:
  name: irrelevant
spec:
  template:
    spec:
      tolerations:
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
      containers:
      - name: stackit-cloud-controller-manager
        env:
        - name: STACKIT_SERVICE_ACCOUNT_KEY_PATH
          value: /etc/serviceaccount/serviceaccount.json


