apiVersion: v1
kind: Service
metadata:
  name: irrelevant
  labels:
    cilium.lbaas/network: "2cfdfdf1-7c5e-4e2e-adc6-79f4b413ceee"
spec:
  type: LoadBalancer
  loadBalancerClass: cilium.stackit.cloud
