apiVersion: v1
kind: Service
metadata:
  name: irrelevant
  labels:
    cilium.lbaas/network: "832b848d-8673-4f78-a404-2f8d4c93eace"
spec:
  type: LoadBalancer
  loadBalancerClass: cilium.stackit.cloud
