apiVersion: v1
kind: Namespace
metadata:
  name: cilium-lbaas
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-controller
  namespace: cilium-lbaas
  labels:
    app: lb-controller
spec:
  selector:
    matchLabels:
      app: lb-controller
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lb-controller
    spec:
      serviceAccountName: lb-controller
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      volumes:
        - name: stackit-creds
          secret:
            secretName: stackit-cloud-secret
            items:
              - key: serviceaccount.json
                path: serviceaccount.json
      containers:
      - name: lb-controller
        image: ghcr.io/hown3d/cilium-lb/lb-controller
        args:
          - --project-id=f5debc67-cfeb-403a-9d92-36fdbe3325c7
          - --network-id=832b848d-8673-4f78-a404-2f8d4c93eace
        imagePullPolicy: IfNotPresent
        env:
          - name: STACKIT_SERVICE_ACCOUNT_KEY_PATH
            value: /.stackit/serviceaccount.json
        volumeMounts:
          - mountPath: /.stackit
            name: stackit-creds
---
